### ISSUE TITLE
RelayListener connects, but TallyArbiter errors

### ISSUE THREAD

**Issue by scoobiekw** [josephdadams/TallyArbiter-RelayListener#1]
RaspPi 4, 4Gb. Both RelayListener and TallyArbiter are on the same machine.

Tally Arbiter working as expected. M5Stick and Web working correctly.

When RelayListener connects to TallyArbiter it logs this error.

0|TallyArbiter  | [Tue Oct 06 2020 13:44:30 GMT-0500 (CDT)]     Caught exception: TypeError: Cannot read property 'id' of undefined
0|TallyArbiter  | TypeError: Cannot read property 'id' of undefined
0|TallyArbiter  |     at Socket.<anonymous> (/home/pi/tallyarbiter/index.js:513:15)
0|TallyArbiter  |     at emitTwo (events.js:126:13)
0|TallyArbiter  |     at Socket.emit (events.js:214:7)
0|TallyArbiter  |     at /home/pi/tallyarbiter/node_modules/socket.io/lib/socket.js:528:12
0|TallyArbiter  |     at _combinedTickCallback (internal/process/next_tick.js:132:7)
0|TallyArbiter  |     at process._tickCallback (internal/process/next_tick.js:181:9)

Both programs built from source on 2020.10.06

**Comment by josephdadams** [comment]
This is actually a bug in the server. I have it fixed but haven't pushed an update yet. The workaround is to make sure your device IDs are actually valid device IDs within Tally Arbiter. (If you use the default config file that I supply with this repo, those are my device IDs and therefore not valid on your server.)

**Comment by scoobiekw** [comment]
Ok. Thanks. I'll watch for an update in the repo too.

**Comment by josephdadams** [comment]
This should be fixed in the main repo. Can you test and file an issue there if not fixed?
